name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1
    -
	    name: Login to Docker Hub
	    uses: docker/login-action@v1
	    with:
	      username: ${{ secrets.DOCKER_HUB_USERNAME }}
	      password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    -
      name: Build, tag, and push image to DockerHub
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t phantomnuker/python-multiarch-test:$IMAGE_TAG \
        --push \
        .
